import Head from 'next/head';
import Header from './../components/Header';
import Nav from './../components/Nav';
import requests from "../utils/requests";
import Results from "../components/Results";


export default function Home({results}) {
  
  return (
    <div>
      <Head>
        <title>hulu</title>
        <meta name="description" content="Generated by TITech Africa" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  )
}

//Server side rendering
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log("genre ", genre);
  console.log("context.query", context.query);
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
